version: "3"
services:
  php:
    container_name: php
    build: ./docker/php/
    networks:
      - backend
    volumes:
      - ./public/:/var/www/html/
      - ./logs/php/:/usr/local/etc/logs/
  apache:
    container_name: apache
    build: ./docker/apache/
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public/:/var/www/html/
      - ./logs/apache/:/usr/local/apache2/logs/
  mysql:
    container_name: mysql
    build: ./docker/mysql/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${LAMP_MYSQL_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - ./dbdata/:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${LAMP_MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_VERBOSE: lamp-mysql
    networks:
      - frontend
      - backend
    ports:
      - "81:80"
networks:
  frontend:
  backend:
