FROM mysql:8.0

COPY mysql.cnf /etc/mysql/conf.d/


# ENV MYSQL_ROOT_PASSWORD=${LAMP_MYSQL_ROOT_PASSWORD}
# ENV MYSQL_DATABASE=${LAMP_MYSQL_DATABASE}

# COPY database.sql /docker-entrypoint-initdb.d/init.sql